### ISSUE TITLE
Why do operations start if their dependencies have failed?

### ISSUE THREAD

**Issue by eliOcs** [danthorpe/Operations#110]
Even though the condition `NoFailedDependenciesCondition` exists, I can't figure a case when it is useful for an operation to start if its dependencies have failed. What is the use case for this behaviour and why is it the default behaviour.

**Comment by danthorpe** [comment]
Hi - firstly, thanks for the feedback.

This is a bit of a recurrent gotcha, there was a previous issue which touched on it here: https://github.com/danthorpe/Operations/issues/77

`NSOperation` doesn't have the concept of failure - operations start and then finish. If they are cancelled in time, their `main()` function isn't executed. With this mechanism, operations with dependencies start when all their dependencies finish.

The concept of finishing with a error (which is easy to think of as a "failed" end state) is added to `Operation` but it doesn't fundamentally change how `NSOperation` or `NSOperationQueue` works.

This is why the `NoFailedDependenciesCondition` exists - so that an operation can enforce that all of it's dependencies finished without any errors or cancellations.

There are some extra classes/conditions in this framework (compared to Apple's sample code) to help you manage whether an operation should be executed at run time, e.g. `BlockCondition` and `GatedOperation`.

Happy to hear suggestions on improvements in this regard though, as I appreciate that it's a bit of a subtle behavior. I'm currently mulling over whether to re-write `Operation` without subclassing `NSOperation` (and provide interop via another mechanism) to solve underlying issues like this.

**Comment by eliOcs** [comment]
Thanks for your reply!

I completely understand that the current implementation is heavily influenced on the NSOperation implementation. When it comes to real life examples it is useful for operation to produce errors and results.

Nice to hear you are working on an improvement :+1:
