### ISSUE TITLE
[Discussion] Mechanism for piping/chaining operation results.

### ISSUE THREAD

**Issue by difujia** [danthorpe/Operations#135]
The execution of one operation sometimes require the result from another operation. For example,  an operation that uploads apns token to a server requires the acquisition of the token by another operation. An operation that saves objects to core data may require the result from a networking operation followed by a parsing operation. The common pattern seen in these scenarios is that data is created by an operation/operations, and goes through a pipe of processing operations in order. Now, thankfully, this framework already provides an elegant way to express the ordering of operations. I think it's worth investigating how operations can pipe their successful results in a generic and compositable fashion.

**Comment by danthorpe** [comment]
This is a really interesting idea - I like it, formalized dependency injection. 

Personally, I have been using a `GroupOperation` with a single child to start the first operation, and then add the 2nd after taking the results from the first. This approach has the advantage that it's easier to re-use & compose, but I does also add a bit more cognitive load (and another queue). See [`ReverseGeocodeUserLocationOperation`](https://github.com/danthorpe/Operations/blob/development/Sources/Features/iOS/LocationOperations.swift#L244) for an example of this.

The nice idea with this approach is that it could reduce quite a bit of boiler plate from these common situations which perhaps don't warrant re-use. The danger would be that it's probably easier to create un-ruly FRP style chains of work (which I think can become hard to maintain). 

So, here is how I'd envision this working from the framework consumer point of view...

```swift
let download = DownloadResource()
let use = UseResource()
use. injectResultFromDependency(download) { (operation, dependency, errors) in
    operation.resource = dependency.resource
}
queue.addOperations(download, use)
```

This would work by conforming `UseResource` to a protocol, and then providing `injectResultFromDependency ` in a default extension.

We can go further for the really common case of a single result being piped by making `DownloadResource` conform to a generic protocol, so that the setter block in the `injectResultFromDependency` is done automatically.

```swift
protocol InjectedOperationType { }

extension InjectedOperationType {
    func injectResultFromDependency<T: NSOperation>(dependency: T, setterBlock: (operation: Self, dependency: T, errors: [ErrorType]) -> Void) {
        // etc
    } 
} 

protocol ResultOperationType {
    typealias Result
    var result: Result? { get }
}

protocol AutomaticInjectedOperationType: InjectedOperationType {
    typealias Requirement
    var requirement: Requirement? { get set }
}

extension AutomaticInjectedOperationType {
    func injectResultFromDependency<T: NSOperation where T: ResultOperationType, T.Result == Requirement>(dependency: T) throws {
        // etc
    } 
}
```

To actually make this work, the framework would just call `addDependency` and add an `OperationObserver`.

For error handling, we can return the errors the dependency finished with to the setter block. For the default / automatic setter - this would have to be interpreted as throwing an error I think.

For cancellation - standard behavior would kick in I think?

Obviously would have to come up with consistent names among "pipe", "chain" "inject"?

Anyone got any other thoughts? /cc @difujia

I've got time today - can put together a PR for further discussion.

**Comment by jshier** [comment]
That looks very interesting. So far I've been trying to minimize any dependencies, and when unavoidable, have created various `*Token` protocols and conforming classes (classes because references are the only way this works) so that I can share a token between all of the operations, with each operation added their values when they complete. A more formalized paradigm would be nice. This looks pretty good but I'd have to try it out to see how well it works for me.

**Comment by danthorpe** [comment]
@jshier :+1: will put together a feature branch for this. 

I think, in general dependency injection is a good thing that should be encouraged, There is a bit of a barrier to doing this *correctly* with `GroupOperation` so this is a nice formalized way for the framework to provide a lightweight methodology for injecting results into operations. So, it's worthy of adding I think.

**Comment by danthorpe** [comment]
Made a start on an implementation for this, can we move discussion of this over to #137. Thanks!

**Comment by danthorpe** [comment]
Implemented & merged.
