### ISSUE TITLE
ResultOperationType not included with iOS extension target

### ISSUE THREAD

**Issue by JamieWhite** [danthorpe/Operations#182]
Any reason for this?

I'm also not even sure how the extension target builds without this because it's referenced in the code.

**Comment by danthorpe** [comment]
Hi Jamie -- sorry about this. I think the extension project might just be out of sync. Are you using master or development branch?

**Comment by JamieWhite** [comment]
yeah I'm running off of development. 

I've been thinking about these different projects. Would it make more sense to split all the none extension stuff into a separate framework within the same repo? So have like Operations.framework (core stuff) then Operations_App.framework

**Comment by danthorpe** [comment]
Yes, when I did it at the time, I knew that it would be a huge PITA to keep them in sync. I spect a fair bit of time looking though how to use a custom modulemap so that stuff that was iOS only, or "non-extension" would be in a different module, i.e.

```swift
import Operations // This would be API extension compatible
import Operations.Application // This would be non-API extension compatible
import Operations.Application.iOS // ?? Maybe for example?
``` 

But... at the time, I thought Carthage was going to resolve the issues, and hopefully SwiftPM will bring about even greater changes to how it's structured.

However, these are taking time, so it's possibly time to look at our options again. Unfortunately I've let the API extensions compatible stuff get out of sync - and I don't even have specific tests in CI for building that project. So, this is what I propose (to happen on Sunday at the earliest unless I can get it done tonight, or if you can submit a PR)

In one ticket:
1. Update `.ci/scripts`, `.ci/buildkite` and `.fastlane/Fastfile` to add tests for iOS extensions project.
2. Update the project to include all the correct files.

Then....
1. Update to latest Carthage - does it help us?
2. Ask in Swift Mailing lists about suggested or possible approaches.
3. Refactor to see if we can make a workspace with nested projects? (as per your suggestion?)

Thoughts?
