### ISSUE TITLE
UIOperation navigation Controller wrapping

### ISSUE THREAD

**Issue by seancatkinson** [danthorpe/Operations#194]
Should we be wrapping all presented view controllers other than UIAlertController in a navigationController?

I would suggest that we add UISplitViewController, UITabBarController and of course UINavigationController to the list of unwrapped presented view controllers - or add an additional parameter to the method with a default value of true as to whether to wrap or not so that consumers can easily override.

I'd also maybe suggest renaming the operation? UIOperation sounds like an operation that will be performed on the main thread rather than an operation that performs navigation.

Finally, we might also want to add a dismissing/popping operation as well as showing/presenting.

**Comment by danthorpe** [comment]
Hi @seancatkinson - thanks for the suggestions & input!

Yes, you are correct that `UIAlertController` is not the only `UIViewController` subclass which should avoid being contained in a `UINavigationController`. Your list looks about right - but another argument/parameter is clearly the better way to go (and test) :+1: - a PR fixing this with tests would be great :+1:

Regarding the name, and really, the entire class... I actually meant to make `UIOperation` an internal class before I released v2.6 but it must have dropped off my radar. It was only added to support the presentation of controllers using AddressBook.framework, Contacts, and of course `AlertOperation`.

However, if you have some `Operation` subclasses which you think are general purpose enough to be useful to others, send me a PR and we can discuss it further.

Personally, I'm a little bit hesitant to add any more UI related functionality to the framework. This is mostly because it's a pretty slippery slope of replicating UIKit behaviors - and isn't really a direction I want this project to go in.

**Comment by danthorpe** [comment]
Closing this now as #196 has been merged which addresses this issue.
