### ISSUE TITLE
Ideal way for Error handling

### ISSUE THREAD

**Issue by vamsiac** [danthorpe/Operations#238]
What would be the best way to handle errors using this framework?
I know that errors array come back  along with the failed operation object, but would like to know better way to display these errors to the users.

Scenario:
1. You make a network connection in airplane mode
2. Operation's completion handler will be called with operation and errors `[My_App.ReachabilityCondition.Error.NotReachable]`.

how should be display this error to the user to make more sense to them.

**Comment by danthorpe** [comment]
Hi @vamsiac - this is a really good question! Unfortunately I don't really have a good answer for you, certainly not a "silver bullet" kind of thing.

I think one think that would certainly make sense - would be to develop/evolve your own `ErrorType` protocol. Which you can then use inside your app more effectively.

For example:

```swift
protocol MyErrorType: ErrorType {
    var underlyingError: NSError? { get }
    var severity: Severity { get }
    var userInfo: NSDictionary? { get }
    var localizedTitle: String? { get }
    var localizedMessage: String? { get }
    var handler: ErrorHandler? { get }
}
``` 

You could then create (on iOS) an `AlertOperation` subclass which can be initialized with something conforming to this:

```swift
class MyErrorAlertOperation: AlertOperation {
    init(error: MyErrorType) {
       // construct an appropriate alert for the user from the error
   }
}
```

This will get you to the point where you can present the user with alerts. However, you might also want to create a special operation observer, to do this more automatically?

There is some great docs from  about recovering from received NSError instances - I would read those as a starting point, as it might give you some ideas about what sort of things you need if you want to display useful errors to the user.

**Comment by vamsiac** [comment]
Thanks Dan, that helps. will try that.

**Comment by danthorpe** [comment]
I think it's work highlighting that `NSError` is an excellent class to encapsulating error information for displaying to the user - and there is no need to re-invent the wheel.

But, also in Swift, `ErrorType` and the error handling mechanisms of Swift 2.0 conflate programmatic error and also recoverable errors - so figuring out a way to manage these which probably have different purposes is worthwhile.

**Comment by vamsiac** [comment]
Dan,

I also noticed that "operationDidFinish" is replaced with the  "willFinishOperation", I might be facing a problem because of this.

Say I call PostOperation which posts data to the server.
when there is an error after posting information I was finishing the operation with that error. 
This was working fine as far as I know when I was using "operationDidFinish"

But with the "willFinishOperation", operation is finishing even before I call finish on it.

```
                task = NSURLSession.sharedSession().uploadTaskWithRequest(request, fromData: body) { (data, response, error) -> Void in
                    self.uploadFinished(data, response: response, error: error)
                }
```
```
    func uploadFinished(data: NSData?, response: NSURLResponse?, error: NSError?) {
        if let downloadedData = data {
            
            let json = try! NSJSONSerialization.JSONObjectWithData(downloadedData, options: []) as? [String: AnyObject]
            
            if json?["StatusCode"] as? String == "UNAUTHORISED",
            let desc = json?["Description"] as? String {
               //operation is already finished by the time it reaches here
                finish(LoginOperation.Error.AuthorizationDenied(desc: desc))
            }
      ........
```

**Comment by danthorpe** [comment]
Basically, from within an `Operation` instance, you always call `finish(error: ErrorType?)`. 

The `willFinishOperation` and `didFinishOperation` are methods which are sent to observers before and then after the state of the Operation changes during the `finish` method. So, you, the framework consumer *never* calls `willFinishOperation` or `didFinishOperation` - these are called on the appropriate observers by `Operation` itself.

Additionally, the method `finished()` is also called here, which can be overridden in subclasses.

The two observers are for very specific things. The `willFinishOperation` is used by `GroupOperation` so that new operation instances can be added to the queue, to prevent the group from finishing.

So, if you have an operation, and you want to handle an error that it finishes with - you can use a `DidFinishObserver`:

```swift
let post = PostOperation()
post.addObserver(DidFinishObserver { op, errors in
    // can do something with the errors here - but note that "op" (i.e. the
    // PostOperation) will have actually finished.
})
queue.addOperation(post)
```

However, if you want to do something with the operation, *right* before it finishes, then you can add a `WillFinishObserver` - these are both block observers.

```swift
let post = PostOperation()
post.addObserver(WillFinishObserver { op, errors in
    if !errors.isEmpty {
        op.produceOperation(PresentErrorOperation(errors))
    }
})
```
For example...

Note that the array of errors is the same for both observers.

Note also - that the framework is very flexible, and there is almost certainly more than one way to do what you want to do.

Hope I've answered your question!

**Comment by vamsiac** [comment]
Yes Dan, the framework is very flexible and there is always more than one way of handling things. Your suggestion above seems to be sensible. I will follow this and let you know how it goes.

**Comment by danthorpe** [comment]
Okay @vamsiac  - I'm gonna close this for now. If you have any more feedback you want to share, that would be great - we can reopen this issue is there is more that can be done as far as the framework goes.
