### ISSUE TITLE
Clearer documentation regarding operation queue

### ISSUE THREAD

**Issue by DavidNix** [danthorpe/Operations#257]
It was unclear to me I had to use Operations custom `OperationQueue` to schedule operations instead of the standard `NSOperationQueue`.  My operations where not executing and I spent a good while trying to figure out why.

**Comment by danthorpe** [comment]
Hi @DavidNix - sorry that the requirement of `OperationQueue` was not as clear for you as it should be. I've added #259 to include this as part of the the `MyFirstOperation` code sample in the README. Hopefully that addresses your issue?

Out of curiosity, in your *good while* figuring out why it wasn't working, did you look at [the programming guide](https://operations.readme.io/docs)? The use of `OperationQueue` is mentioned in pretty much the first paragraph on the first page. And this guide itself is linked to right at the top of the README of this repo. I ask, because I'm not 100% about keeping this guide, as it's not very discoverable (maybe because it's not on GitHub). I'm wondering about moving it all across to the wiki pages her, as it would be better for it to be versioned with the repo.

**Comment by DavidNix** [comment]
@danthorpe I extensively read your programming guide.  But I completely missed that part about using your custom `OperationQueue` subclass in the introduction.  I typically jump straight to example code.  

You're guide is some of the best documentation I've seen for a 3rd party library.

You're spot with including usage of `OperationQueue` in the `MyFirstOperation` example.  Thank you!

**Comment by danthorpe** [comment]
@DavidNix great - thanks, going to close this now!
