### ISSUE TITLE
Add relationship among operation conditions.

### ISSUE THREAD

**Issue by difujia** [danthorpe/Operations#261]
Hi @danthorpe,

By now the condition mechanism is very straightforward for expressing the readiness of an operation. I'd like to make it a little bit more complex in order to suit more use cases. 

Currently a condition has on idea about other conditions hosted by the same operation. In some cases, it would make no sense to evaluate a condition if another condition  is not satisfied, especially when these conditions have some side effect (e.g. present alerts when not satisfied.). 

Say I have an operation which needs condition A to ensure current user has logged in, and another condition B to ensure current user has enabled a particular service. Both of these conditions could self-satisfy by generating an operation which presents UI to give user an opportunity to do these activities. When the user hasn't logged in, the prompt of condition B shouldn't appear.

Current condition implementation is a bit weak on this use case because the order of evaluation is unspecified, and all conditions will be evaluated regardless of the results of others. In the above example, I'd like to have condition A being the prerequisite of condition B. So condition B would not generate dependency and be evaluated unless condition A is satisfied.

So far I have used a workaround to achieve this. The real operation has condition B installed, and is composed in a `ComposedOperation` which hosts condition A. This approach needs a lot of boilerplate, and is very confusing to others (who knows the exact intention of composing composed operations.).

**Comment by danthorpe** [comment]
Hi @difujia - firstly, as always thanks for your contributions and suggestions 😀

I think that yes, conditions are incredibly powerful, and they have the potential to be even more so.  Adding relationships, dependencies, or even nested conditions could and probably will happen. One of the things which I've been thinking about for a v3 of this framework is a re-write of `Operation` as a base protocol with a class implementation which does not inherit from `NSOperation`. Given this, framing "conditions" as a variant of such a protocol, and essentially making it a specialist form of an `Operation` dependency, would open up the current feature set of `Operation`s to conditions. Which I think would cover all of the features you've hinted at here.

Of course, it is still possible to use the current architecture to do the sort of things you are suggesting here too - I think it would mean a "doubling down" on the current architecture which I'm a little hesitant to do. I guess we'll need to discuss it more.

Lastly, I'll add here, that I think you can do what you want in this scenario with condition A and condition B, by making the operation mutually exclusive. We made some changes in v2.6 which would mean that adding a condition which has a dependency to a mutually exclusive operation, will add the exclusive-ness around the condition's dependency. Check out the Operation Changes in the [release notes](https://github.com/danthorpe/Operations/releases/tag/2.6.0) and the pull requests themselves: #157 and #159. So.. I think with some consideration for how your `HasUserLoggedInCondition` and `LogUserInOperation` then you can make it so that the user is only presented with one log in operation and both conditions will pass before your target operation runs, without using `ComposedOperation`.

And all of this leads me back to, I guess my main point. Which is that, I think as it stands the order of execution of operations & conditions is quite subtle, so I'm hesitant to further complicate it. Rather, I would prefer to elevate condition to be be an `Operation` type itself in order to both simplify the architecture (operations just have dependencies) and support the kind of sophistication you want here.

Thoughts? Anyone else? @jshier @mblsha @itsthejb @bastianschilbe @estromlund ?

**Comment by danthorpe** [comment]
@difujia - any more comments on this?

**Comment by difujia** [comment]
@danthorpe I'm very happy to see that this project is moving to the next milestone, good job 💪.

I think it would take a bit of time for v3.0 to come out, so in the meanwhile I'm trying to build the relationship bits on top of current infrasturcture. Once I've got some decent progress, I will open a new PR for discussion. So I think you could close this as you wish.

**Comment by danthorpe** [comment]
@difujia - okay, will be interested to see how it goes!

Regarding v3 - although I've been meaning to make a start on it for a while. I am kinda hoping that I'll be able to have it done or close to being done by WWDC - so that when Swift 3.0 comes out, we'll be looking at a v4 of Operations.

**Comment by danthorpe** [comment]
This is now basically possible in `development` - conditions can now be subclasses of `Condition` which is an `Operation`. You can do everything with conditions that you can with operations, including adding conditions, multiple dependencies, observers and result injection.

Also, regarding this specific problem / use case. I think the best solution is to write a custom `CapabilityType` for your account login. Then you should be able to use the standard `AuthorizedFor` condition & `Authorize` operation. Will get back to your on this with a fuller example.

**Comment by itsthejb** [comment]
Hi Dan. Sorry I couldn't give any input into this - we're getting close to our final release date now, might have some headspace after that to make some contributions....!

**Comment by danthorpe** [comment]
@itsthejb - no worries. As you firm up your app for your release - keep an eye on the Release notes for this project. There is release candidate for v2.10, and then v3.0 has some breaking changes.

**Comment by itsthejb** [comment]
That's a good point, I should certainly review the change logs...

**Comment by danthorpe** [comment]
@itsthejb change log for v2.10 (not yet merged) is [here](https://github.com/danthorpe/Operations/pull/298/files?short_path=4ac32a7#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)
