### ISSUE TITLE
Error & Alert handling examples

### ISSUE THREAD

**Issue by ryanjm** [danthorpe/Operations#264]
I think the documentation is lacking in some best practices around error handling and how to present alerts.

For example, if you have a group operation, `UpdatePostsOperation`, that creates multiple operations under it, `UpdatePostOperation`, how should the errors be handled? You might only use the group operation in one part of the code and the normal operation in another part. In the first part, you only want to present one alert/error for the entire group. But in the second case you want to make sure the normal operation is able to present an alert as well.

Is it best to attach an observer to the "top" operation (whether it be the group or normal operation depending on the use case) and have that observer handle the error/alert? How does it get information about the error? Right now it looks like `finish()` only takes [ErrorType](https://github.com/danthorpe/Operations/blob/a2a2b6c8ef0e8e5816887984962121f96b5b1382/Sources/Core/Shared/Operation.swift#L538) not `NSError`s. Additionally there isn't any documentation around how to create addition ErrorTypes or how those are expected to be used.

When creating a `BlockCondition` there isn't any information on how to define what error should be passed in the case of a failure. Same goes for the other conditions.

Also, when should an operation be cancelled vs just finish with errors?

Once I get a better handle on these topics I'd be happy to write up pages for the documentation (is that on Github as well?).

**Comment by danthorpe** [comment]
Hi @ryanjm - I agree with you that there are improvements that can be made on best practices with regard to error handling. You are now the 2nd person to ask this question: https://github.com/danthorpe/Operations/issues/238

You have some really good questions here, and I don't think there are any definitive answers. As with everything in programming, it is a matter of tradeoffs.

But a couple of quick thoughts on this:

1. The APIs of this project is very much pre-Swift 2.0 - especially with regard to error handling. Some of these will start to change, for example changing `BlockOperation` to accept a throwing block, and then automatically catching & finishing the operation. Beyond this, for v3 I want to rewrite `Operation` as a base class and full embrace Swift 2.0 architecture design, especially with protocols and `ErrorType`. Do I have a timeline for this? Not really, my current aim is to get there before WWDC, with a v4 to correspond with Swift 3.0 later in the year (I'm assuming there will be breaking changes).

2. `NSError` conforms to `ErrorType` - you can finish with instances of `NSError` with a problem. To "handle" them you will always need to perform some kind of `as? MyErrorType` type casting. See my answers to the previous question about creating your own custom error types.

3. Yeah, regarding `BlockCondition` - for sure it's a bit weak in this regard - could be updated to accept `() throws -> Bool`. I guess just because the condition fails - it's not necessarily an error in the condition. The operation finish with an error, the error being that the condition was false. Can address this as an enhancement I think. It's similar to `BlockOperation` error producing capability.

4. I personally think that the `cancellation` should only be used as a result of user action. Things like, tapping a cancel button, but also in some cases navigating off a screen or sending the app to the background might mean that an operation is cancelled. I use finish, with errors, when there is actually an error - sometimes these errors are environmental errors (and recoverable from), sometimes programming errors - should not be recovered from.

Regarding the documentation. There is a [programming guide](http://operations.readme.io), which is hosted by Readme.io - but I'm going to move it all across to the wiki I think so that it is versioned inside the repo, and is more discoverable. Hopefully will get this done over the weekend - it's on my list.

If you make notes or write something up, then I would really really really appreciate the additions 😁👍 I can add:
1. your pages to the Readme site
2. your pages the wiki pages here if I've moved it all across.
3. a link to a blog post in the README if you write your thoughts up in a blog?

In all honesty - it would be great if some people wrote blog posts about this project, and how they're using it. Putting the wiki to use here for best practices, submitted & curated by the many people who use this project (over 140 apps now) is one of the goals.

**Comment by ryanjm** [comment]
@danthorpe Sorry for not finding the other question, but thanks for pointing it out.

Re blog posts / write up for wiki: That also sounds good. Once I get my head around these topics and we finish implementing it in our project I'd be happy to do both.

Thanks for the information about `ErrorType` & `NSError`, I guess I should have looked closer :smile:. And I'll look at trying to write a better `BlockCondition` or `BlockOperation` to handle throwing errors. I'm still getting my feet wet with Swift.

**Comment by danthorpe** [comment]
No problem.

One other thing which I'm just thinking about, trying out is *having a dedicated Slack team/channel* for discussion on Operations.

I've previously used Gitter - but lets face it, people use Slack, and I'm more likely to be signed into Slack to respond to people. So if you use Slack, see if you can join https://danthorpe.slack.com/ there is an `#operations` channel.

**Comment by danthorpe** [comment]
Also - totally aware how weird, pretentious, ego-driven, self-serving it is having a Slack channel for my own open source projects. But it just seems like the most sensible thing to do to encourage more free flowing discussion about these things.

**Comment by jshier** [comment]
Says I need a login and password, though I don't know how open Slack channels are supposed to work.

**Comment by danthorpe** [comment]
@jshier - yeah, neither do I actually. I'm reading up.... but I can invite you directly.

**Comment by ryanjm** [comment]
People have to be invited to a Slack group. There are [rails sites](https://github.com/outsideris/slack-invite-automation) setup to help automate that process (I'm not endorsing that one, just the first one that showed up)

**Comment by danthorpe** [comment]
Okay, will look at getting slackin (or equivalent) setup for this. Although happy to invite people directly too. @jshier - you should have received an email.

**Comment by danthorpe** [comment]
Hi! I think we've covered everything here - gonna close this.
