### ISSUE TITLE
Behavior of produceOperation is inconsistent in GroupOperation.

### ISSUE THREAD

**Issue by difujia** [danthorpe/Operations#272]
I've just noticed the change and I know this is intended. But I would still like to point out that this makes `produceOperation` and `addOperation` be identical on `GroupOperation`, which in turn produces redundancy. More importantly, this change has made no way for `GroupOperation` to really produce an operation that does not belong to this group. I think the old behavior would still be needed in some use cases. For example, when each operation in a group finishes, the group operation may need to produce an operation that does something with the fact. Also, when a group operation finishes, it may produce another group operation to process the results of its succeeded/failed child operations. Moreover, `produceOperation` is marked final, but its behavior varies depending on the type of the operation. This looks like an a anti-pattern of the use of `final`. If we really need the varied behavior, we should override `produceOperation` in `GroupOperation`, which I still do not feel good though.

**Comment by danthorpe** [comment]
Hi @difujia - thanks for the feedback on this. 

Yes, it was intentional - I'll need to look back at the history for the details on this. I don't have any objections to restoring the original behavior. Absolutely agree that as it stands it currently "breaks" `finally`.

I will investigate the reasoning behind the change, and the impact and get back to you.

**Comment by danthorpe** [comment]
@difujia - this has now been fixed as part of #326.
