### ISSUE TITLE
iOS Extensions Operations scheme overrides iOS Operations scheme with carthage

### ISSUE THREAD

**Issue by ffittschen** [danthorpe/Operations#279]
Hi,
I tried to use the `NetworkObserver` and wondered, why Xcode showed the error "Use of unresolved identifier 'NetworkObserver'".

When building the framework with carthage, it first builds the `iOS Operations` scheme and afterwards it builds the `iOS Extensions Operations` scheme which overrides the framework in the `Carthage/Builds` folder.

```
$ carthage bootstrap --platform iOS --no-use-binaries
*** Checking out Operations at "2.9.0"
*** xcodebuild output can be found in /var/folders/lh/tds7c6z4419c1m11psl5f3500000gn/T/carthage-xcodebuild.1ouTCe.log
*** Building scheme "iOS Operations" in Operations.xcodeproj
*** Building scheme "iOS Extensions Operations" in Operations_ExtensionCompatible.xcodeproj
```

Is there any way to avoid this behaviour?

**Comment by danthorpe** [comment]
Hi @ffittschen - thanks for your feedback!

Yeah, this is a bit of a problem which we've had for a while ☹️😔. It's due to the way that Xcode outputs it's products & Carthage builds targets.

We have an existing issue for this: #112  At the moment, I suggest forking the repo - and deleting the xcodeproj which you don't want. 

Unfortunately, I don't know how this will actually be resolved. I hope that when SwiftPM is more mature, then this can be solved with something like nested modules. E.g. `import Operations.App.iOS` or something. 

If you have any ideas please add comments into #112 - I'm going to close this as a duplicate.
