### ISSUE TITLE
Passing data from a GroupOperation to its child operations

### ISSUE THREAD

**Issue by plm75** [danthorpe/Operations#291]
Hello, I loved the WWDC talk and I'm glad to see you did such a great work turning it into such a nice library.  So thank you 👍 

I have an `OpBoostrap` GroupOperation composed of an `OpFetch` and an `OpParse`.
`OpParse` is dependent on `OpFetch`'s results and is itself a GroupOperation.

In pseudo code:

    class OpBootstrap: GroupOperation
        init
            let opFetch = OpFetch(url: "http://some_url")
            let opParse = OpParse()
            opParse.injectResultFromDepency(opFetch)
            super.init(operations: [opFetch, opParse])
 
    class OpFetch: Operation, ResultOperationType
        // wrapper around an Alamofire call
  
    class OpParse: GroupOperation, AutomaticInjectionOperationType
        var requirement: JSON?
        init
            // here, requirement == nil 
           // I cannot do something like : let someOp = SomeOp(data: requirement)
          super.init(operations:[])

        override func execute
            // here, requirement != nil, and I can do:
           let someOp = SomeOp(data: requirement)
           addOperation(someOp)
        
Adding operations in `execute` seems to work, but doesn't "feel right".  Is this the only way for a GroupOperation to pass data to its `child` operations or is there a better way ?

**Comment by danthorpe** [comment]
Hi @plm75 - thanks for the feedback, and the question - it's a good one!

I think you're pretty much there with the result injection stuff. I agree that it's not 100% fantastic because you really want to be able to inject requirements at initialization time. So, adding operations to the group during the execute is pretty much acceptable - and it's how some of the groups work in the original WWDC sample code.

There is one additional option though...

```swift
class OpParse: GroupOperation, AutomaticInjectionOperationType {
    var requirement: JSON? = .None

    override init(operations: [NSOperation]) {
        let someOp = SomeOp() // no data init
        super.init(operations: [someOp])
        addObserver(StartedObserver { [unowned someOp] operation in 
              someOp.data = operation.requirement
        })
    }
}
```

Essentially, adding an observer for did start to the group, which can then set it's (received) requirement on any child operations.

Thoughts? Happy to get more feedback on this of course if you have ideas for improvements!

**Comment by danthorpe** [comment]
Gonna close this for now. @plm75 please re-open if you have more feedback.
