### ISSUE TITLE
NetworkObserver flickers when called multiple times

### ISSUE THREAD

**Issue by ryanjm** [danthorpe/Operations#335]
I've got a beautiful set of operations which create many more operations, but each of them make `NetworkObserver` an observer of their operation. As far as I can tell, because I'm calling it multiple times, that triggers strange animations.

I've created a GIF from a video that shows the network indicator restarting each time it is called (at least I believe that is what is happening):

![2016-06-07 17_28_18](https://cloud.githubusercontent.com/assets/90015/15879050/4e18bfe0-2cd5-11e6-9010-ce5abd355470.gif)

It looks like the `NetworkObserver` was (possibly) loosely based on this [SO answer](http://stackoverflow.com/a/6978817/130556) or at least they are using a similar strategy. The main difference between the two is:

[NetworkObserver 66-68](https://github.com/danthorpe/Operations/blob/ecf45018e8e10cbd20b14493b929189cd8b3dd83/Sources/Core/iOS/NetworkObserver.swift#L66-L68):

```swift
if activityCount > 0 {
    networkIndicatorShouldShow(true)
}
```

SO Answer:

```objc
if (activityCount == 0) {
    [self setNetworkActivityIndicatorVisible:YES];
}
```

By doing `> 0` it is actually triggering `networkActivityIndicator.networkActivityIndicatorVisible` multiple times. I think by changing that to `== 0` it will make sure it only gets triggered once and that the timer is actually updated more than just when the timer finishes.

**Comment by ryanjm** [comment]
I have a proposal for how to change those four methods (`updateIndicatorVisibility`, `networkIndicatorShouldShow`, `networkActivityDidStart`, `networkActivityDidEnd`). I want to run it by @danthorpe before I create a PR with this type of change.

```objc
private func showNetworkIndicator {
    if activityCount == 0 {
        networkActivityIndicator.networkActivityIndicatorVisible = true
    }
    activityCount += 1
}

private func hideNetworkIndicator {
    activityCount -= 1
    if activityCount <= 0 {
        networkActivityIndicator.networkActivityIndicatorVisible = false
        activityCount = 0
    }
}

// Public API

func networkActivityDidStart() {
    assert(NSThread.isMainThread(), "Altering network activity indicator state can only be done on the main thread.")
    showNetworkIndicator()
}

func networkActivityDidEnd() {
    assert(NSThread.isMainThread(), "Altering network activity indicator state can only be done on the main thread.")
    hideNetworkIndicator()
}
```

This does leave out the `visibilityTimer` aspect. I think it could be worked in, I just don't know what the intention was behind that. If you have a long running activity that doesn't trigger another network observer update (to refresh the timer) it seems like the timer would turn the indicator off after a second. Is it a matter of knowing when an operation cancels and then decrementing the counter (`hideNetworkIndicator`)?

**Comment by blg-andreasbraun** [comment]
Hi @ryanjm,
the intention behind the timer is to create a 1 second delay before hiding the indicator when no network request ist running anymore. That is done to prevent it from flickering on and off in situations where you have network operations in sequence.

**Comment by danthorpe** [comment]
Hi @ryanjm - thanks for the feedback - definitely think that we need to do something to fix this flickering issue! 

Anyway, looking through the code, I think the whole observer, indicator, timer etc could be improved significantly. Additionally, given your animation, and experience with it, it seems like the timer is not working as intended? 

I'm was sort of half thinking that changing the whether the network indicator is visible or not should be an `Operation`. And the network observer can use `OperationQueue.mainQueue()`. Then, instead of just switching the state to show/hide, we would instead push some operations onto the queue. Something like this for showing the indicator.

[ Delay 0.5 ] <-- [Show] <-- [Delay 0.5]

However, your proposals would also work - the downside is that it complicates the business logic a bit for how the show/hide happens, which is then harder to test. Part of the beauty of Operations, is that we can remove/simplify business logic into small units which we compose or schedule together.

Anyway, pretty happy for your to proceed with a PR as you suggest 😁

**Comment by ryanjm** [comment]
Ok, so it sounds like the timer should only be created/set when `activityCount == 0`.

I'll create a fork and play around with reworking that code / tests to see what I can do to help. With the concept of the timer in mind, I'll see what makes the most sense.

@danthorpe I'm not sure I understand your suggestion about the change to using an `Operation`. How would you keep track of the current `activityCount`?
