### ISSUE TITLE
Order of precedence in Mutual Exclusivity

### ISSUE THREAD

**Issue by DeFrenZ** [danthorpe/Operations#364]
There's a behaviour I found in mutual exclusivity management that I didn't expect and not sure if intended, but intuitively I'd say it's not.

From what I've seen anything that has a mutual exclusivity condition it basically takes the precedence on it the moment it's added to the queue (compared to operations that will be added later). This can be an issue though because other operations produced later with the same exclusivity could have to be completed before, and thus creating an operations deadlock.

Example:
- create operation A
A is dependent for completion on operation C, which it produces on execution
C has MutualExclusivity<ME>
- create operation B
- B.addDependency(A)
- B.addCondition(MutualExclusivity<ME>)
- do a GroupOperation(operations: [A, B])

My opinion on this is that MutualExclusivity should reserve the resource when evaluating and not the moment it's added to the queue, conceptually talking. Though this might just be considered programmer error.

A workaround is (instead of adding both operations to the queue at the same time):
- do a GroupOperation(operations: [A])
- A.addObserver(WillFinishObserver { group.addOperation(B) })

**Comment by danthorpe** [comment]
Hi @DeFrenZ  - sorry, I did read this when you posted it, then I got distracted by something else I guess. I will get back to you this week. Very possible that it's a bug, or something not being communicated effectively.

**Comment by danthorpe** [comment]
Hi @DeFrenZ, 

Totally agree with your "mutual exclusivity should be captured at the time of execution, rather than adding to queue". At the moment when an `Operation` is added to the queue, if there are conditions, and if there are conditions which are mutually exclusive, we add each to the manager (and setup the observer to remove it). And all of this is thread-safe.

However, technically, rather than adding the operation to the manager at this point, which essentially adds the lock, we could instead perform this inside a `WillExecuteOperation` block observer. So, that all we do at `addOperation` is setup any dependencies (where we must wait for previous mutually exclusive operations to end), and then add two observers, one for adding mutual exclusivity and another for removing it.

This would essentially allow you add mutually exclusive operations whenever you want to a queue and the mutual exclusion would be triggered as a result of their own ready state (i.e. it would fall out of the dependency ordering) instead of the add to queue ordering.

**Comment by danthorpe** [comment]
Hi @DeFrenZ - did a bit of thinking about deferring the mutually exclusivity lock in #394. As you can see from the changes, and the discussion, this is not a direction we want to do in. It effectively puts the burden of exclusivity onto the framework consumer to setup via dependencies, which defeats the whole purpose.

I think, as with all tools, some of them are sharp, and need to be used carefully.
