### ISSUE TITLE
The lint run script makes useless changes in 2 files

### ISSUE THREAD

**Issue by gsimmons** [danthorpe/Operations#374]
This marks my repo as dirty, which is annoying. :)
(this is with the 3.0.0 release)

**Comment by danthorpe** [comment]
@gsimmons - which two files?

**Comment by gsimmons** [comment]
Guess that would be useful information.

Sources/Core/Shared/GroupOperation.swift
Sources/Core/Shared/Queue.swift

It’s removing spaces on a couple of empty lines.

**Comment by danthorpe** [comment]
@gsimmons - this is fixed in `development`, gonna push out 3.1 soon, but I'm not going to do a build point release for white space.

The reason this happened is that a contributor didn't have SwiftLint installed - which means that the white space wasn't fixed - but you have it installed, so you get these changes when you build the framework

I could take a look into tweaking CI so that SwiftLint fails on whitespace issues - but... I don't know, not sure I want to require that of contributors!
