### ISSUE TITLE
Possibility to allow one kind of a operation in a queue

### ISSUE THREAD

**Issue by fuxx** [danthorpe/Operations#375]
After reading through the documentation and the code i am asking myself if its possible to prevent that a specific operation can be added multiple times to a operation queue.

As far as i understand the MutuallyExclusive condition only prevents that operations of the same kind can run in parallel, but they do not prevent that a operation can be queued twice in a operation queue.

Is there any condition i could use or has someone a hint how i could achieve this behaviour?

An example scenario could be to download data from a specific URL via a fetch() method, which could be triggered from multiple sources. After download a notification is sent and multiple receivers have to reload them self with the new data. With MutuallyExclusive the fetch() would add the operation multiple times to the queue and after each operation the next of the same kind would be started right after and the notification would be send again. I would like to run the operation only once and drop all others as long as one of the same kind is in the same queue. 

Thanks in advanced 👍

**Comment by danthorpe** [comment]
Hi @fuxx - this is quite an interesting idea!

Unfortunately, _Operations_ cannot do this - the logic is actually pretty tricky to do generally, and edge cases abound. More than likely it's always going to be something that a client should manage themselves.

I expect that you would need to write a custom condition which would check some state/storage to determine whether or not to perform the download. If the state says it's okay (consider first use, and after data is stale) - perform the download. The `Download` operation would have to write to the state storage and send notifications before it finishes.

Another option would be to use `NSURLCache` with the appropriate cache control to prefer local cached data - then inspect the `NSURLResponse` so that the "download" operation cancels itself if it received cached data. Now, there is the possibility of a race condition here (relying on the thread safety of `NSURLCache`) which I'm not sure on.

Other less favourable options would be your own `Queue` type system which manages this internally itself.

So, in essence, the best way forward, is to make your `Download` operation smart enough to be able to read from and write to some state, where you'll want to store a flag or a timestamp. This state will need to be read-many, write-one thread safe. There is an internal class [`Protector<T>`](https://github.com/danthorpe/Operations/blob/development/Sources/Core/Shared/ThreadSafety.swift#L45) which you can use for inspiration on this.

**Comment by fuxx** [comment]
Hi @danthorpe thanks for the extensive feedback. I think your approach suggestions make sense and i will think some time about the implications of each. Maybe if i can come up with generic way i will let you know, but for some further thoughts it was a good input.

Thanks for the inspiration!
