### ISSUE TITLE
Module 'Operations' has no member named 'LocationCapability'

### ISSUE THREAD

**Issue by SkylerSeamans** [danthorpe/Operations#380]
Building 3.0.0 via Carthage. I can't seem to access Capability.Location or LocationCapability.

let authorize = Authorize(Capability.Location(), completion: { (success: Bool, status: CLAuthorizationStatus) in

})
ERROR: Type 'Capability' has no member 'Location'

**Comment by SkylerSeamans** [comment]
I'm using the iOS target build. For what it's worth, the Photos capability works in my project.

**Comment by danthorpe** [comment]
Hi @SkylerSeamans - when you run `carthage` what do you do?

If you have this in your `Cartfile`:

> github "danthorpe/Operations"

and you execute:

```
carthage bootstrap
```

You should see:

> *** Cloning Operations
> *** Downloading Operations.framework binary at "3.0.0"
> *** xcodebuild output can be found in /var/folders/xd/007m649n6wq4x7p2wy0kyq480000gn/T/carthage-xcodebuild.YUpWUj.log

This uses the standard distribution (vs the API extension compatible version). And your above code will compile.

If you are compiling _Operations_ locally, due to the way Frameworks are named, and Carthage builds everything it can see - this is results in the standard distribution being overwritten by the API compatible version (which doesn't have location services). This is discussed in a bit more detail in these [release notes](https://github.com/danthorpe/Operations/releases/tag/2.9.1). There is an open issue here too: #112 - it is going to get resolved, it's just that it's a non-trivial huge change.

**Comment by danthorpe** [comment]
Also - just FYI, in your callback, you've written `(success: Bool, status: CLAuthorizationStatus)` which is potentially misleading. The `status` will indicate authorised or not authorised, and the boolean is an indicator of whether location services is even enabled on the device. The boolean is not a success indicator. This is better code:

```swift
let authorize = Authorize(Capability.Location()) { enabled, status in
    // do something here            
}
```

Also, it's generally easier to just use the `AuthorizedFor` condition:

```swift
operation.addCondition(AuthorizedFor(Capability.Location(.WhenInUse)))
```

**Comment by SkylerSeamans** [comment]
Works great. Thanks for the help!
